### ISSUE TITLE
Camelcase filename not working on case-sensitive servers

### ISSUE THREAD

**Issue by ralfgoeke** [jbeyerstedt/kirby-plugin-kirbytextRaw#1]
Hi,

when the filename is written in camelcase (kirbytextRaw.php) the plugin is not working on case sensitive servers. Renaming the file to kirbytextraw.php fixes this issue.

Thx for your plugin! :)

**Comment by jbeyerstedt** [comment]
I`m quite shure, that my server is case sensitive and I have no problem at all. On my local environment (OS X) and at my hoster uberspace, which is a centOS 6.7 install.

Of course it will not work, if you call this plugin all lower case `->kirbytexteaw()` instead of `->kirbytextRaw()`.

**Comment by ralfgoeke** [comment]
Tried to call `kirbytextRaw()` without success. Only renaming the file worked. It's been working on my OSX MAMP locally, but not on HostEurope (Linux).

Maybe it depends on some server configuration?

**Comment by tweh** [comment]
Unfortunately I encounter an camel case issue on my server after this commit.

At the moment this is how you wrote it

   plugins/kirbyTextRaw/kirbytextraw.php -> Method kirbytextRaw()

which is three different versions of _camelcasing_. On my server these variants worked

```
plugins/kirbytextRaw/kirbytextRaw.php -> Method kirbytextRaw()
```

or

```
plugins/kirbyrextraw/kirbytextraw.php -> Method kirbytextRaw()
```

So maybe it is a good idea to make everything in all lowercase except the method name.

**Comment by jbeyerstedt** [comment]
The plugin should be located in `site/plugins/kirbytextraw/kirbytextraw.php`, because Kirby is not happy, if the folder name and the file name are not the same.
But the folder `kirbyTextRaw` must be your interpretation, because it is not mentioned in my plugin.

But you are right, the last commit demands, that you (manually) change the folder name you copied/ linked/ cloned this repository to.

**Comment by tweh** [comment]
Ups … sorry the wrong folder name was my fault O:-) Thanks.

Schönes Wochenende!
