### ISSUE TITLE
Markdown not processed

### ISSUE THREAD

**Issue by PeteCrighton** [jbeyerstedt/kirby-plugin-kirbytextRaw#9]
I have to append `ktr()` instead of replacing `kirbytext()`, like so:
```
$page->title()->kirbytext()->ktr()
```
Otherwise the `<p>` tags would be correctly stripped, but no Markdown would be processed. Can you recreate the problem? Am I missing something?

**Comment by jbeyerstedt** [comment]
Sorry, the last pull-request somehow missed to call the kirbytext function, but only processed the text itself.

**Comment by PeteCrighton** [comment]
No problem, thanks for the prompt fix!
